### ISSUE TITLE
Creating a geospatial range within metadata

### ISSUE THREAD

**Issue by EOGrady21** [tdwg/dwc-qa#205]
I am representing a dataset which was collected between a range of spatial points (zooplankton images captured from a towed instrument). I do not have the exact lat/lon points for each individual record, but want to capture the range within the event level metadata. Is there a standard way to extend metadata names? Such as decimalLatitudeStart decimalLatitudeEnd? 

(I'm very new to dwc, thank you for your patience and advice!)

**Comment by sformel-usgs** [comment]
Welcome to the DwC world and I'm glad you're taking the time to ask these questions!  

Here is some good advice from the OBIS manual: https://manual.obis.org/common_qc.html#uncertain-geolocation
and some similar material from the GBIF IPT manual: https://ipt.gbif.org/manual/en/ipt/latest/data-quality-checklist#where-did-the-event-take-place

In short, you probably want to use the [`footprintWKT`](https://dwc.tdwg.org/terms/#dwc:footprintWKT) term to define a line or polygon, instead of designating a point via `decimalLongitude` and `decimalLatitude`.

**Comment by EOGrady21** [comment]
Thank you! I appreciate your time to answer my questions.
