### ISSUE TITLE
iDigBio distinctValues 6 files missing count

### ISSUE THREAD

**Issue by debpaul** [tdwg/dwc-qa#54]
6 files in iDigBiodistinctValues https://github.com/tdwg/dwc-qa/tree/master/data/idigbioDistinctValues
missing the count. These are:
1. basisOfRecord
2. behavior
3. establishmentMeans
4. geodeticDatum
5. license
6. occurrenceStatus

Files I cannot check (too large to View, and can't wait for dwnload): preparations, reproductiveCondition, typeStatus

Looking good overall - thanks for making these happen!

**Comment by godfoder** [comment]
Hi Deb, it turns out those file actually do have counts in them. When viewed on github, the first column is too large ,so the count column gets scrolled off the side of the table. If you scroll all the way down to the bottom of the file, you should see a horizontal scroll bar. You can also probably scroll horizontally by using shift+scroll, or possibly by clicking on the table and using the left and right arrow keys (both of those work on chrome, other browsers may use different keys).

**Comment by debpaul** [comment]
Aha! Thanks @godfoder for figuring this out, and explaining how to see the counts! I'll close this ticket.
